### PR TITLE
[documentation/Fix] add documentation for huggingface feature and fix ocr_predictor model loading

### PR DESCRIPTION
**Pull request by felixdittrich92**
This PR:

- adds documentation how to use the huggingface integration (load / push)
- add tables for community models

- fix for passing a model itself directly to the predictor

Issue:
#426 (can be closed after merge)

- [ ] TODO: rework text in documentation

Review:
Code: @charlesmindee 
Documentation:  @fharper 

Any feedback is welcome :)

### CODE REVIEW

**Comment by felixdittrich92** [comment]
@fharper let me know your ideas to improve this part of documentation for the community :+1:

**Review by charlesmindee — APPROVED** [review]
Thanks for that, waiting for @fharper to review the doc part!

**Comment by charlesmindee** [comment]
is the "TODO: rework text in documentation" OK ?

**Comment by fharper** [comment]
As mentioned to @felixdittrich92, I'll review today or worse case tomorrow :)

**Review by fharper — APPROVED** [review]
Content LGTM (I wasn't able to generate the doc caused I still have issues on my M1 even following the steps from someone else)

**Comment by fharper** [comment]
@charlesmindee: can you validate and update the labels please.

**Pull request merged**
