### PR TITLE
fix: pymupdf version

### PR DESCRIPTION
**Pull request by charlesmindee**
This PR allows the PyMuPDF version to be 1.18.15 for in-house compatibility issues.

Any feedback is welcome!

### CODE REVIEW

**Review by fg-mindee — COMMENTED** [review]
Before changing this, we need to ensure that version 1.18.11 is compatible. Because here enlarging the constraint will always install (in the CI) the latest, meaning 1.18.15. Can you confirm that you can run all unittests in `1.18.11`? :pray:

**Comment by charlesmindee** [comment]
It is indeed not working with 1.18.11, it works since the 1.18.13

**Review by fg-mindee — DISMISSED** [review]
Perfect thanks! Two things:
- let's do the same type of check when we want to update some dependency specifiers
- if you have a clear idea of the justification of the upper & lower bounds of the specifier, could you add an inline comment in the `setup.py`? (that will be easier for next time)

**Review by fg-mindee — APPROVED** [review]
Perfect thanks!

**Pull request merged**
