### PR TITLE
[Fix] Pin py3.11 for MacOS latest / update publish version checks

### PR DESCRIPTION
**Pull request by felixdittrich92**
MacOS: 
https://github.com/actions/setup-python/issues/855 
https://github.com/actions/setup-python/issues/865

### CODE REVIEW

**Comment by felixdittrich92** [comment]
print(doctr.__version__) instead

**Comment by felixdittrich92** [comment]
@odulcy-mindee We could apply this as temp fix because i think the fix in setup-python takes longer as expected :)

**Review by odulcy-mindee — COMMENTED** [review]
What about pin macos version to `macos-13` instead, as suggested here ?
https://github.com/actions/setup-python/issues/855

**Comment by felixdittrich92** [comment]
> What about pin macos version to `macos-13` instead, as suggested here ? [actions/setup-python#855](https://github.com/actions/setup-python/issues/855)

@odulcy-mindee In this case we would need to update the required CI jobs 

The repo says for python:

```
5 most popular major.minor versions
```

So i expect a fix for this in a future release that we can easily change this back, without updating our required CI jobs.

That's also the reason why i would prefer the py3.11 pin over the maco-13 pin :)

**Comment by odulcy-mindee** [comment]
> @felixdittrich92 In this case we would need to update the required CI jobs

Aaaaaah, that's true :-(

Ok, let's keep it like that

**Review by odulcy-mindee — APPROVED** [review]

**Pull request merged**
