### PR TITLE
[Bug] fix straighten pages 

### PR DESCRIPTION
**Pull request by felixdittrich92**
This PR:

- fix rotate condition for straighten pages
- fix new shapes after straightening pages
- ruff recommendations

Any feedback is welcome :hugs:

### CODE REVIEW

**Review by odulcy-mindee — APPROVED** [review]
LGTM, thank you !

**Comment by felixdittrich92** [comment]
> LGTM, thank you !

WB 😊

**Comment by odulcy-mindee** [comment]
Haha, thanks ^^

**Comment by felixdittrich92** [comment]
@odulcy-mindee Could you check your Slack please if you have the time :sweat_smile: : :+1:

**Pull request merged**
