### PR TITLE
feat: Added remaining components of DBNet

### PR DESCRIPTION
**Pull request by fg-mindee**
Following up on #261, this PR introduces the following modifications:
- renamed `linknet` into `linknet16`
- added all remaining components to the pytorch implementation of DBNet
- added PyTorch version of Resize transform
- refactored the detection module as such:

1. each model gets its own subfolder
```shell
├── core.py
├── differentiable_binarization
│   ├── base.py
│   ├── __init__.py
│   ├── pytorch.py
│   └── tensorflow.py
├── __init__.py
├── linknet
│   ├── base.py
│   ├── __init__.py
│   └── tensorflow.py
└── zoo.py

```
2. the init dynamically selects the corresponding PyTorch/TF submodule
3. the `base` part implements everything that doesn't require a framework
4. the `pytorch` / `tensorflow` submodule allows the import for the framework bits

- fixed typing annotations in recognition models
- updated documentation
- updated unittests

Any feedback is welcome!

### CODE REVIEW

**Review by charlesmindee — DISMISSED** [review]
Thanks for this refactoring!

**Comment by fg-mindee** [comment]
For simplicity, #314 will need to be merged first

**Review by charlesmindee — DISMISSED** [review]
Thanks for the PR

**Review by charlesmindee — APPROVED** [review]
Thanks!

**Pull request merged**
