### PR TITLE
[api] upgrade fastapi and uvicorn and configure actions

### PR DESCRIPTION
**Pull request by felixdittrich92**
This PR:

- upgrades fastapi and uvicorn to latest version
- add delay (for model loading) and move docs ping at the end

Any feedback is welcome :hugs: 

Issue:
#847

### CODE REVIEW

**Comment by felixdittrich92** [comment]
I have no problems that's really a bit weird :sweat_smile: 

```
(work) felix@felix-GS66-Stealth-11UH:~/Desktop/doctr$ curl -I http://localhost:8002/docs
HTTP/1.1 200 OK
date: Wed, 13 Jul 2022 12:17:07 GMT
server: uvicorn
content-length: 942
content-type: text/html; charset=utf-8
x-process-time: 0.0002713203430175781
```

**Comment by frgfm** [comment]
I'll have to run tests more specifically : the fact that the tests succeeded this time seems to indicate that there are some conflicts in the loose version range that we allowed earlier

I solved similar problems recently on another project, I'll check this. But the message here is: I think this PR is not solving the previous issue :/

**Comment by felixdittrich92** [comment]
@frgfm with old versions it passes also :sweat_smile: Also locally i was not able to reproduce this issue

**Comment by felixdittrich92** [comment]
Closed with #997

**Pull request closed without merging**
