### PR TITLE
change the way model is saved in ddp

### PR DESCRIPTION
**Pull request by venkatapathy**
Checkout
1. https://discuss.pytorch.org/t/how-to-save-a-single-final-model-from-distributed-multi-gpu-training/130983
2. https://stackoverflow.com/questions/5097456/throw-away-local-commits-in-git

### CODE REVIEW

**Comment by felixdittrich92** [comment]
Hi @venkatapathy :wave: 

Thanks for opening this :+1: 
Could you please remove the `.gitignore` changes ?

**Comment by venkatapathy** [comment]
I have deleted the .gitignore. Can you please check now? Thanks

**Comment by felixdittrich92** [comment]
@venkatapathy you have deleted the whole please delete only the two lines you have added

**Review by venkatapathy — COMMENTED** [review]
I hope this is fine?

**Comment by felixdittrich92** [comment]
@venkatapathy please restore the last line in `.gitignore` see: https://github.com/mindee/doctr/pull/1289/files
than it's fine 👍

**Comment by venkatapathy** [comment]
thanks. i have done it :)

**Review by felixdittrich92 — APPROVED** [review]
Thanks for the fix 👍

**Pull request merged**
