### PR TITLE
[chore]: clean dependencies

### PR DESCRIPTION
**Pull request by felixT2K**
This PR:

- updates API dependencies
- remove upper bounds for dev dependencies
- increase minimum tf2onnx version to fix the incompatibility with >tf2.12

### CODE REVIEW

**Review by odulcy-mindee — COMMENTED** [review]
I don't know why it passes the tests but [there is an incompatibility between some packages](https://github.com/mindee/doctr/actions/runs/5995836517/job/16259453924?pr=1287):

```
...
#11 137.0 ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
#11 137.0 cleo 2.0.1 requires rapidfuzz<3.0.0,>=2.2.0, but you have rapidfuzz 3.2.0 which is incompatible.
...
```

See `Build & run docker` steps

**Comment by felixT2K** [comment]
> I don't know why it passed the tests but [there is an incompatibility between some packages](https://github.com/mindee/doctr/actions/runs/5995836517/job/16259453924?pr=1287):
> 
> ```
> ...
> #11 137.0 ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> #11 137.0 cleo 2.0.1 requires rapidfuzz<3.0.0,>=2.2.0, but you have rapidfuzz 3.2.0 which is incompatible.
> ...
> ```
> 
> See `Build & run docker` steps

Yeah i saw this also but it runs locally inside docker also without issues ... i think we override repidfuzz with our >=3.0.0 version and it seems not to break anything inside cleo or there is no use of it

**Comment by felixT2K** [comment]
@odulcy-mindee checked again it overrides it:  rapidfuzz-3.2.0   is installed and all works 😅

**Comment by felixT2K** [comment]
cleo lib ref: https://github.com/python-poetry/cleo/commit/57c6b9ee79164c099aed385413566ac3f3d2af4e (as i wrote on LinkedIn ^^)

**Review by odulcy-mindee — APPROVED** [review]

**Pull request merged**
