### PR TITLE
[classification] Fix cfgs

### PR DESCRIPTION
**Pull request by felixdittrich92**
This PR fixes the following:

- some classification models have had not `cfg` now they have :sweat_smile: 
- also the updating was not correct

Any feedback is welcome :hugs: 

Needs to be pushed before: #881  Otherwise the upload from trained classification models to HF hub wont work

### CODE REVIEW

**Review by charlesmindee — COMMENTED** [review]
Hi @felixdittrich92, thank you for this PR!
Before merging, I just have a question:
I don't understand why you need to add the "classes" entry in the model and in the cfg ?

**Comment by felixdittrich92** [comment]
@charlesmindee 
This has no functional impact but if we save the model and it's corresponding cfg in #881  to the hf hub its really confusing to see the french (default) vocab in the classes but model was trained on maybe germn (108 num_classes). 
So it's just there so that the configuration looks correct and there are no misunderstandings

**Review by charlesmindee — APPROVED** [review]
Thanks for that!

**Comment by frgfm** [comment]
@charlesmindee missing PR labels here as well :)

**Pull request merged**
