### PR TITLE
Improve pypdfium2 integration again

### PR DESCRIPTION
**Pull request by mara004**
pypdfium2 now implements automatic closing on garbage collection (since v3.3).
Using documents in a context manager has been deprecated to avoid inadvertent closing in wrong order.

Also removed a type check which, I think, is unnecessary. pypdfium2 already checks the input and raises a TypeError accordingly.

### CODE REVIEW

**Comment by mara004** [comment]
The `tran-char-classification` test failure appears unrelated.

black wants this change, though:
```diff
-    renderer = pdf.render_to(
-        pdfium.BitmapConv.numpy_ndarray,
-        scale=scale,
-        rev_byteorder=rgb_mode,
-        **kwargs
-    )
+    renderer = pdf.render_to(pdfium.BitmapConv.numpy_ndarray, scale=scale, rev_byteorder=rgb_mode, **kwargs)
```

**Review by felixdittrich92 — APPROVED** [review]
Thanks @mara004 LGTM :+1:

**Comment by felixdittrich92** [comment]
Could you push an empty commit please to trigger CI again ? :)

**Comment by mara004** [comment]
> Could you push an empty commit please to trigger CI again ? :)

Done. I probably shouldn't have skipped CI in the first place, but thought it kind of a waste of energy to re-run all the checks just because of black formatting.

**Comment by felixdittrich92** [comment]
> > Could you push an empty commit please to trigger CI again ? :)
> 
> Done. I probably shouldn't have skipped CI in the first place, but thought it kind of a waste of energy to re-run all the checks just because of black formatting...

Yeah i totally agree the thing is that @charlesmindee is the only one currently with repo maintainer rights so i can merge it only if the CI pass 😅

**Comment by mara004** [comment]
Sure, I see :)

**Comment by mara004** [comment]
Looks like `train-char-classification` failed again for unrelated reasons.

**Comment by felixdittrich92** [comment]
FYI you do not need to change any code if you only want to trigger CI you can use:
git commit  --allow-empty

:)

**Comment by felixdittrich92** [comment]
> Looks like `train-char-classification` failed again for unrelated reasons.

That's ok we know the issue and have it in track this job fails everytime currently 👍

**Comment by mara004** [comment]
> git commit --allow-empty

Thanks, didn't know that yet!

**Comment by felixdittrich92** [comment]
Thanks for the update :hugs:

**Comment by felixdittrich92** [comment]
No, I really appreciate that. 👍 
We just have to be careful to keep it backwards compatible to avoid problems like the `render_to_pil` breaking change we have had. 😅

**Comment by mara004** [comment]
Yeah, in this case the previous code stills work of course, and should continue to do so until pypdfium2 4.0 at least (if that ever happens).
However, the new code now requires a minimum of pypdfium2 3.3 because of the automatic closing thing.

So what matters is basically
* me not doing backwards incompatible changes within one major version
* doctr restricting the allowed pypdfium2 versions accordingly

**Pull request merged**
