### PR TITLE
fix: Trying to fix API template

### PR DESCRIPTION
**Pull request by frgfm**
Following up on #847, this PR introduces the following changes:
- updates version pin for fastAPI & uvicorn to debug API template

Any feedback is welcome!

### CODE REVIEW

**Comment by frgfm** [comment]
Mmmh it looks like there are several dependency issues 🤔

**Comment by frgfm** [comment]
@felixdittrich92 to the best of my knowledge, the dependabot is helpful to make you keep this up to date, but it doesn't take breaking changes into account 🤔 So I doubt it would work

**Comment by felixdittrich92** [comment]
@frgfm mh yes .. btw pinning httptools to 0.1.2 solves the dependency conflict and i think if we run compose as root could solve the docs issue

**Comment by frgfm** [comment]
> @frgfm mh yes .. btw pinning httptools to 0.1.2 solves the dependency conflict and i think if we run compose as root could solve the docs issue

I cannot run the docker correctly with my current setup, but once I get my hands on my new one, I'll be able to get back into docker and fix this 👍  (within a few weeks max)

**Comment by felixdittrich92** [comment]
Hi @frgfm :wave: do you think we can close this ? .)

**Comment by frgfm** [comment]
Sure!

**Pull request closed without merging**
