### PR TITLE
Error in unpacking archive of SROIE dataset

### PR DESCRIPTION
**Pull request by HamzaGbada**
Fixing the unpacking archive of SROIE dataset.

### CODE REVIEW

**Comment by felixdittrich92** [comment]
Test:
https://github.com/mindee/doctr/blob/51c42373bbd989808ebc23ef0709dee5a706c3ec/tests/pytorch/test_datasets_pt.py#L272

needs also an update:
```
(mock..., None, "sroie2019_train_task1.zip")
```
Same for the Tensorflow test case :)

**Review by felixdittrich92 — APPROVED** [review]
Thanks for the fix @HamzaGbada 👍

**Comment by felixdittrich92** [comment]
Hey @HamzaGbada :wave:,

i saw that we have the same issue for CORD dataset are you interessted to fix this also maybe ? 
Same changes would be required like in this PR :)

**Comment by HamzaGbada** [comment]
> Hey @HamzaGbada wave,
> 
> i saw that we have the same issue for CORD dataset are you interessted to fix this also maybe ? Same changes would be required like in this PR :)

@felixdittrich92 SURE

**Pull request merged**
