### PR TITLE
fix: Fixed MASTER recognition architecture

### PR DESCRIPTION
**Pull request by fg-mindee**
This PR introduces the following modifications:
- fixed PyTorch implementation of MAGC module
- refactored MASTER to use `magc_resnet31` backbone added to available backbones, and adds `pretrained_backbone` option
- fixed TF compatibility with AMP for MASTER
- updated unittests accordingly

Any feedback is welcome!

### CODE REVIEW

**Review by charlesmindee — APPROVED** [review]
Thanks!

**Comment by fg-mindee** [comment]
Actually, the paper references the ResNet31 architecture which has 256 channels in stage 2, but in the MASTER paper (Table1) they modified the stage 2 to have 512 channels.

So I reverted back those changes and added back the URL & benchmark perf

**Review by charlesmindee — APPROVED** [review]
Thanks for the revert

**Review by charlesmindee — APPROVED** [review]
Thanks!

**Pull request merged**
