### PR TITLE
[deps] upgrade to tf 2.9 and remove keras

### PR DESCRIPTION
**Pull request by felixdittrich92**
This PR:

- updates tf to >=2.9
- removes keras
- change mean/std magc tf

Note: this upgrade triggers a lot of mypy issues i would say we handle this in another PR @frgfm wdyt ?
Same for TF mobilenet onnx issue

Otherwise if we want to fix the mypy issues in this PR i would be really happy to get some helping hands :hand: 

Any feedback is welcome :hugs: 

Todo: reduce the evaluate_detection CI runtime

### CODE REVIEW

**Comment by felixdittrich92** [comment]
really weird i cannot reproduce this behaviour locally :sweat:

**Comment by frgfm** [comment]
I would highly suggest to only update the requirements (potentially check whether removing the version specifier of keras doesn't cause harm) to close #932

This is a rather big change (for users I mean), so I wouldn't mix it with other modif unless they're directly related :)

**Comment by felixdittrich92** [comment]
> I would highly suggest to only update the requirements (potentially check whether removing the version specifier of keras doesn't cause harm) to close #932
> 
> This is a rather big change (for users I mean), so I wouldn't mix it with other modif unless they're directly related :)

@frgfm yes i agree with only update tf / maybe remove keras and fix the mypy stuff. 
But we have to decide how we want to handle the (now) failing tests for TF onnx export models (mobilenet).
We could revert it for the moment complete or only exclude mobilenet models wdyt ?

**Comment by felixdittrich92** [comment]
tackled by #963

**Pull request closed without merging**
