### PR TITLE
[docs] Rework documentation [new style / features / structure]

### PR DESCRIPTION
**Pull request by felixdittrich92**
This PR updates the current documentation 

- [x] new more modern style (furo)
- [x] dark & light theme / framework split docu
- [x] restructure documentation
- move code of cunduct & contributing to docu
- [x] add sample image grid for each dataset

motivation:
Every active modern library also needs decent documentation, which is the showpiece. Therefore we should improve it (even if it's not fun :sweat_smile:) and try to cover everything as best as possible, including the framework difference

further todo: (maybe in another PR)
- same image additions for transformations 
- read the docs grammar stuff and so on

issues:
#729 could be closed with this

Any feedback is very welcome :hugs: 
@fg-mindee @charlesmindee @SiddhantBahuguna  wdyt ? :smile: 

Examples:
light
dark
light2
contrib

I have also checked how it looks as docstring while coding with the tabs and personally i found it pretty nice to have both snippets at once. The only drawback is the much larger docstring.

### CODE REVIEW

**Comment by fg-mindee** [comment]
That's a very interesting PR :) 

I have to admit, it would have been nice to split it in a few haha

General comments first:
- the code of conduct & contributing markdown cannot be moved (it's for github). But if you need them someplace else, we can create a symlink
- could you explain the new dependencies of the documentation please?
- for the dataset images, I'll add them in a release attachments to limit the amount of content files in the repo
- I see that you use tabs for PyTorch/TensorFlow: it's really neat, I'd love to have that. However, I didn't see how you mean to build this for both framework (you can't build for both of them at once)

**Comment by felixdittrich92** [comment]
@fg-mindee 
Yes i know but the most stuff in this PR depends on other so really hard to minimize 😅 

1. I agree but i would say we hold this also in the documentation so we have this twice but can link in the readme directly to docs. Wdyt?
2. furo is a theme like the old sphinx_rtd_theme and sphinx-tabs is an sphinx extension which i have used to realize the tf/pytorch Code example split :)
3. 👍 than we need only change to the url 
4. Yes i know i have take care of this directly in the docstrings you can check this in any changed model file (for example resnet) :D

**Comment by felixdittrich92** [comment]
@fg-mindee 
Point 3:  zip file with dataset image-grids attatched
[dataset_image_grid_examples.zip](https://github.com/mindee/doctr/files/8235744/dataset_image_grid_examples.zip)

**Comment by fg-mindee** [comment]
Would it be possible to split this into several PRs please? :pray: 
- one for the change of theme + JS/CSS
- updating the docstrings of datasets with images
- the rest in a final PR

That would help reducing the amount of files modified here :sweat_smile:

**Review by fharper — APPROVED** [review]
LGTM

**Comment by fg-mindee** [comment]
Now that all the subPRs have been merged, this PR can be closed :)
Thanks a lot for your time @felixdittrich92 :pray: This is a huge improvement to the general look of the documentation!!

**Comment by fharper** [comment]
@felixdittrich92: thanks for this update, I really love the new visual!

**Pull request closed without merging**
