### PR TITLE
lint: :lipstick: mypy and black

### PR DESCRIPTION
**Pull request by odulcy-mindee**
Fix lint with `mypy` and `black`.

Also replaced `use_auth_token` by `token` in `doctr/models/factory/hub.py`, see https://github.com/huggingface/huggingface_hub/pull/1122

### CODE REVIEW

**Review by felixdittrich92 — CHANGES_REQUESTED** [review]
Thanks @odulcy-mindee 

`api/imgjpg `can be removed and `api/requirements-dev.txt` and `api/requirements.txt` should be added to gitignore :)

**Comment by odulcy-mindee** [comment]
> Thanks @odulcy-mindee
> 
> `api/imgjpg `can be removed and `api/requirements-dev.txt` and `api/requirements.txt` should be added to gitignore :)

Oops, good catch ! Thanks !

**Review by felixdittrich92 — APPROVED** [review]
Thanks :)

Are you sure that `docker compose` instead of `docker-compose `in a Makefile is valid ?

**Comment by odulcy-mindee** [comment]
> Are you sure that `docker compose` instead of `docker-compose `in a Makefile is valid ?

Yeah, now `docker compose` is drop-in replacement of `docker-compose`, see: https://docs.docker.com/compose/compose-v2/#differences-between-compose-v1-and-compose-v2. It's now a plugin which is already in `docker`, we do not need to have a standalone binary.

See also https://github.com/docker/compose#about-update-and-backward-compatibility

**Comment by felixdittrich92** [comment]
> > Are you sure that `docker compose` instead of `docker-compose `in a Makefile is valid ?
> 
> Yeah, now `docker compose` is drop-in replacement of `docker-compose`, see: https://docs.docker.com/compose/compose-v2/#differences-between-compose-v1-and-compose-v2. It's now a plugin which is already in `docker`, we do not need to have a standalone binary.
> 
> See also https://github.com/docker/compose#about-update-and-backward-compatibility

Ah nice and good to know ty :+1:

**Pull request merged**
