### PR TITLE
refactor: Switched from PyMuPDF to pypdfium2

### LINKED ISSUE #486: Consider removing PyMuPDF for dependency that is not AGPL licensed
Hi folks!  Love the project, but the dependency on PyMuPDF can pose a problem for commercial use because of it's AGPL license (I think use of PyMuPDF may technically require the project itself to be GPL licensed, although I'm no expert here). Would you consider integrating a PR that replaces the PyMuPDF dependency with an alternative?

### PR DESCRIPTION
**Pull request by fg-mindee**
This PR introduces the following modifications:
- switched PDF backend from PyMuPDF to pypdfium2
- deprecated annotation reading (not supported by pypdfium2 for now)
- updates unittests & documentation
- only uses PyMuPDF for PDF mocking in the unittests (does impact license for users)

Closes #486

Any feedback is welcome!

### CODE REVIEW

**Review by charlesmindee — DISMISSED** [review]
Thanks for that! I wanted to do it quickly but I am running out of time :sweat_smile: 
Are you sure keeping pymupdf for the tests is not an issue ?

**Comment by fg-mindee** [comment]
> Thanks for that! I wanted to do it quickly but I am running out of time sweat_smile Are you sure keeping pymupdf for the tests is not an issue ?

For pypi downloads, I'm positive since it doesn't ship the test folder. But just to make sure that the entire codebase is rid of this, I changed it to Pillow + docTR synthesize function to mock PDFs :+1:

**Comment by fg-mindee** [comment]
Also it seems that pypdfium2 isn't supported by some versions of Python :thinking: But we'll handle this in another PR

**Review by charlesmindee — APPROVED** [review]
Thanks! It is cool to get rid of pymupdf

**Review by charlesmindee — APPROVED** [review]
thanks!

**Comment by mara004** [comment]
I see that text extraction and image localisation code was removed with this change.

PDFium provides capabilities to extract text from PDFs, but I don't have a support model for it yet in `pypdfium2`. It's a feature that has already been requested several times, and I hope to work on it soon. The [`pdf_text_page`](https://github.com/innodatalabs/pdfbrain/blob/master/pdfbrain/pdf_text_page.py) example from pdfbrain should give a pretty good idea on how to do it.

I'm not sure if PDFium can locate images, but will look it up.

**Comment by frgfm** [comment]
Thanks a lot @mara004, we're quite excited about how thorough you are in the development of this project :)

**Comment by mara004** [comment]
I'm currently working on the text extraction helper class in https://github.com/pypdfium2-team/pypdfium2/pull/110/. If you have any suggestions/requests concerning the API, please let me know.
I've browsed the pdfium code in [`fpdf_edit.h`](https://pdfium.googlesource.com/pdfium/+/refs/heads/main/public/fpdf_edit.h) and believe that locating images would be possible using the functions `FPDFPage_CountObjects()`, `FPDFPage_GetObject()`, `FPDFPageObj_GetType()` and `FPDFPageObj_GetBounds()`. I hope to eventually add a support model for this, too.

**Comment by mara004** [comment]
I have just merged the new support models into main: https://github.com/pypdfium2-team/pypdfium2/commit/bbc2438f0189ae3118fa3aacdaf6120f2827a72b

**Comment by frgfm** [comment]
@mara004 that's great! Do you have any minimal snippet example please? So that I can integrate the feature into docTR 😁

**Comment by mara004** [comment]
I guess something like this:

#### Images
```python3
doc = pdfium.PdfDocument(filepath)
page = doc.get_page(pagenum)
pageobjs = pdfium.get_pageobjs(page)
images = pdfium.filter_pageobjs(pageobjs, pdfium.FPDF_PAGEOBJ_IMAGE)
img_positions = []
for img in images:
    img_positions.append( pdfium.locate_pageobj(img) )
```

#### Text
```python3
doc = pdfium.PdfDocument(filepath)
textpage = doc.get_textpage(pagenum)
text_boxes = []
for bbox in textpage.get_rects():
    text_boxes.append( (bbox, textpage.get_text(*bbox)) )
```

Please also refer to [`test_pageobjects.py`](https://github.com/pypdfium2-team/pypdfium2/blob/main/tests/helpers/test_pageobjects.py) and [`test_textextractor.py`](https://github.com/pypdfium2-team/pypdfium2/blob/main/tests/helpers/test_textextractor.py) for confirmed-to-work examples. The CLI integration code might also be of interest: [`find_pageobjects`](https://github.com/pypdfium2-team/pypdfium2/blob/main/src/pypdfium2/_cli/find_pageobjects.py) and [`extract_text`](https://github.com/pypdfium2-team/pypdfium2/blob/main/src/pypdfium2/_cli/extract_text.py).

**Comment by mara004** [comment]
FYI, I yet made a few changes to the text API in https://github.com/pypdfium2-team/pypdfium2/commit/e40cbb8ae1c62183e411eed296e0544028695538 and adapted the above example.

**Comment by mara004** [comment]
I just released pypdfium2 1.10.0, which contains the new support models.

**Comment by frgfm** [comment]
Can we get people like you as "customer service" for all OSS libraries haha? 😁 
I'll check how to integrate that soon, thanks 🙏

**Comment by mara004** [comment]
I'm glad to help OSS projects as far as my limited knowledge permits :).
Seriously, in the end I think pypdfium2 can only benefit if it gets used more widely, so I aim to make it fit for the needs of embedders. I'm personally working on a python project which depends on PDF rendering quite a lot, so I thought it might be important to consolidate pypdfium2 a bit.

**Comment by mara004** [comment]
The API rewrite I mentioned in the other thread should be finished now, and I plan to release version 2.0.0 of pypdfium2 soon (there's a pre-release already). I will again update the examples above and make a PR for the rendering code.

**Pull request merged**
